image: 'node:carbon'

before_script:
  - 'apt-get update -yq'
  - 'apt-get install -y ruby ruby-dev rubygems-integration'
  - 'gem install sass'
  - 'npm install -g nodemon'
  - 'npm set progress=false'
  - 'npm install --silent'
  
stages:
  - build
  - clean_up
  
build_and_deploy_prod:
  stage: build
  script:
    - 'npm run build'
    - 'gem install dpl'
    - 'dpl --provider=heroku --app=binar-fe-batch-5 --api-key=56a16017-5a3f-4949-894d-696bd7e60c67'
  only:
    - cms-dev
    
clean_up_job:
  stage: clean_up
  script:
    - 'rm -rf node_modules'
    - 'rm -rf ~/.node-gyp'
  when: on_failure